# Generated by Django 4.0.5 on 2022-06-15 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hivemindapi', '0002_alter_event_imgaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='imgAddress',
            field=models.CharField(max_length=2000),
        ),
    ]
